[package]
name = "kvdb"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.29.0"
tempfile = "3.10"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"

[[bin]]
name = "kvdb"
path = "src/main.rs"

[lib]
name = "kvdb"
path = "src/lib.rs"